#if !os(watchOS)
import SwiftUI

struct PromptResultsView: View {
    let results: [PromptResult]
    var onDelete: ((PromptResult) -> Void)?

    var body: some View {
        if !results.isEmpty {
            VStack(alignment: .leading, spacing: 16) {
                Text("Prompt Results")
                    .font(.system(.title2, design: .rounded, weight: .semibold))
                    .foregroundStyle(MapleTheme.textPrimary)

                ForEach(results) { result in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text(result.promptName)
                                .font(.headline)
                                .foregroundStyle(MapleTheme.textPrimary)

                            Spacer()

                            providerBadge(result.llmProvider)

                            if let onDelete {
                                Button(role: .destructive) {
                                    onDelete(result)
                                } label: {
                                    Image(systemName: "trash")
                                        .font(.caption)
                                }
                            }
                        }

                        Text("Generated by \"\(result.promptName)\" prompt — \(providerName(result.llmProvider))")
                            .font(.caption)
                            .foregroundStyle(MapleTheme.textSecondary)
                            .italic()

                        Text(result.result)
                            .font(.body)
                            .foregroundStyle(MapleTheme.textPrimary)
                    }
                    .padding()
                    .background(MapleTheme.surfaceAlt, in: .rect(cornerRadius: 12))
                }
            }
        }
    }

    @ViewBuilder
    private func providerBadge(_ provider: LLMProvider) -> some View {
        let isCloud = provider == .claude || provider == .openai
        HStack(spacing: 4) {
            Image(systemName: isCloud ? "cloud.fill" : "iphone")
            Text(isCloud ? "Cloud" : "On-Device")
        }
        .font(.caption2)
        .foregroundStyle(isCloud ? MapleTheme.info : MapleTheme.success)
        .padding(.horizontal, 8)
        .padding(.vertical, 3)
        .background(
            (isCloud ? MapleTheme.info : MapleTheme.success).opacity(0.12),
            in: .capsule
        )
    }

    private func providerName(_ provider: LLMProvider) -> String {
        switch provider {
        case .appleFoundationModels: "Apple Foundation Models"
        case .claude: "Claude"
        case .openai: "OpenAI"
        case .none: "None"
        }
    }
}
#endif
